INSERT INTO Authors ...

INSERT INTO Categories ...

INSERT INTO Publishers ...

INSERT INTO Books ...

INSERT INTO Members ...

INSERT INTO BorrowRecords ...

INSERT INTO Reservations ...